### ISSUE TITLE
Polystat throw IllegalArgumentException

### ISSUE THREAD

**Issue by APotyomkin** [polystat/polystat#27]
Polystat 0.3.0 throw java.lang.IllegalArgumentException:

I ran base div by zero example with:
```
java -jar target/polystat-0.3.0-jar-with-dependencies.jar sandbox temp
```
And got:
```
Exception in thread "main" java.lang.IllegalArgumentException: Attribute 'EO-Version' not found in MANIFEST.MF file(s) among 18 other attribute(s): ["Build-Jdk-Spec", "Bundle-Descripti
on", "Bundle-ManifestVersion", "Bundle-Name", "Bundle-RequiredExecutionEnvironment", "Bundle-SymbolicName", "Bundle-Vendor", "Bundle-Version", "Created-By", "Export-Package", "Implemen
tation-Title", "Implementation-Version", "Import-Package", "Main-Class", "Manifest-Version", "Multi-Release", "X-Compile-Source-JDK", "X-Compile-Target-JDK"]
        at com.jcabi.manifests.Manifests.read(Manifests.java:274)
        at org.eolang.parser.XeListener.enterProgram(XeListener.java:85)
        at org.eolang.parser.ProgramParser$ProgramContext.enterRule(ProgramParser.java:128)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.enterRule(ParseTreeWalker.java:50)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:33)
        at org.eolang.parser.Syntax.parse(Syntax.java:126)
        at org.polystat.Program.apply(Program.java:85)
        at org.polystat.Program.apply(Program.java:49)
        at org.polystat.far.FaR.errors(FaR.java:76)
        at org.polystat.AnFaR.errors(AnFaR.java:41)
        at org.polystat.Polystat.scan(Polystat.java:152)
        at org.polystat.Polystat.exec(Polystat.java:128)
        at org.polystat.Polystat.main(Polystat.java:69)
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.1`

**Comment by yegor256** [comment]
@APotyomkin should be OK now, try version 0.3.1
