### ISSUE TITLE
goto.eo file not found error

### ISSUE THREAD

**Issue by PetrB09** [polystat/polystat#31]
When i tried to analyze [test.txt](https://github.com/polystat/polystat/files/7822645/test.txt) i got next error:
```
Exception in thread "main" java.lang.RuntimeException: java.io.FileNotFoundException: .\src\goto.eo (Не удается найти указанный файл)
        at org.cactoos.text.UncheckedText.lambda$new$0(UncheckedText.java:67)
        at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:56)
        at org.cactoos.scalar.Checked.value(Checked.java:76)
        at org.cactoos.scalar.IoChecked.value(IoChecked.java:63)
        at org.cactoos.scalar.Unchecked.value(Unchecked.java:56)
        at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:57)
        at org.cactoos.text.UncheckedText.asString(UncheckedText.java:91)
        at org.cactoos.text.Split.<init>(Split.java:154)
        at org.cactoos.text.Split.<init>(Split.java:139)
        at org.cactoos.text.Split.<init>(Split.java:97)
        at org.eolang.parser.Syntax.lines(Syntax.java:159)
        at org.eolang.parser.Syntax.parse(Syntax.java:93)
        at org.polystat.Program.apply(Program.java:85)
        at org.polystat.Program.apply(Program.java:49)
        at org.polystat.AnOdin.resolveObjectHierarchy(AnOdin.java:97)
        at org.polystat.AnOdin.getObjectsHierarchy(AnOdin.java:75)
        at org.polystat.AnOdin.errors(AnOdin.java:47)
        at org.polystat.Polystat.scan(Polystat.java:151)
        at org.polystat.Polystat.exec(Polystat.java:127)
        at org.polystat.Polystat.main(Polystat.java:69)
Caused by: java.io.FileNotFoundException: .\src\goto.eo (Не удается найти указанный файл)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:211)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:153)
        at org.cactoos.io.InputOf.lambda$new$2(InputOf.java:76)
        at org.cactoos.io.InputOf.stream(InputOf.java:310)
        at org.cactoos.io.TeeInput.stream(TeeInput.java:867)
        at org.cactoos.io.InputAsBytes.asBytes(InputAsBytes.java:77)
        at org.cactoos.io.BytesOf.asBytes(BytesOf.java:341)
        at org.cactoos.text.TextOf.lambda$new$0(TextOf.java:297)
        at org.cactoos.scalar.Checked.value(Checked.java:76)
        at org.cactoos.scalar.IoChecked.value(IoChecked.java:63)
        at org.cactoos.text.TextEnvelope.asString(TextEnvelope.java:65)
        at org.cactoos.text.UncheckedText.asString(UncheckedText.java:88)
        ... 13 more
```
But if i add it from cqfn/eo repo this error disappears

**Comment by yegor256** [comment]
@andreoss can you please take a look?

**Comment by andreoss** [comment]
@yegor256 We should pull foreign objects from Objectionary or just skip them?

**Comment by yegor256** [comment]
@andreoss we should pull them, just like we pull `cage` and `stdout` here. I can't understand why `goto` is not being pulled.
