### ISSUE TITLE
Simplest test leads to error

### ISSUE THREAD

**Issue by someilay** [polystat/polystat#43]
EO code:
```
[] > main
  0 > @

[] > test
  main > @
```

I use the latest release .jar

Error:
```
java.lang.Exception: Parent (or decoratee) object "main" of object "test" is specified, but not defined in the program!
        at org.polystat.odin.analysis.EOOdinAnalyzer$$anon$2.$anonfun$analyze$6(EOOdinAnalyzer.scala:65)
        at cats.syntax.EitherOps$.leftMap$extension(either.scala:172)
        at org.polystat.odin.analysis.EOOdinAnalyzer$$anon$2.analyze(EOOdinAnalyzer.scala:65)
        at org.polystat.odin.analysis.EOOdinAnalyzer$.$anonfun$analyzeSourceCode$1(EOOdinAnalyzer.scala:79)
        at fs2.Stream.$anonfun$flatMap$1(Stream.scala:1188)
        at fs2.Pull$FlatMapR$1.unconsed(Pull.scala:994)
        at fs2.Pull$FlatMapR$1.out(Pull.scala:1020)
        at fs2.Pull$.$anonfun$compile$24(Pull.scala:1178)
        at fs2.Pull$.$anonfun$compile$2(Pull.scala:904)
        at analyze @ org.polystat.AnOdin.errors(AnOdin.java:51)
        at get @ fs2.internal.InterruptContext.$anonfun$eval$1(InterruptContext.scala:91)
        at get @ fs2.internal.InterruptContext.$anonfun$eval$1(InterruptContext.scala:91)

No errors found
```

**Comment by nikololiahim** [comment]
Can you try this:
```
[] > test
  [] > main
    0 > @
  [] > test1
    main > @
```

The problem I encountered with Polystat is that it correctly recognizes only those `.eo` files which:
1. Contain only one top-level object
2. This object has the same as the file

The problem here is that the analyzer is given a malformed XMIR which does not contain an object called "main".

**Comment by nikololiahim** [comment]
I'm sure @yegor256 can explain more

**Comment by someilay** [comment]
New error:
```
java.lang.Exception: Parent (or decoratee) object "main" of object "test.test1" is specified, but not defined in the program!
        at org.polystat.odin.analysis.EOOdinAnalyzer$$anon$2.$anonfun$analyze$6(EOOdinAnalyzer.scala:65)
        at cats.syntax.EitherOps$.leftMap$extension(either.scala:172)
        at org.polystat.odin.analysis.EOOdinAnalyzer$$anon$2.analyze(EOOdinAnalyzer.scala:65)
        at org.polystat.odin.analysis.EOOdinAnalyzer$.$anonfun$analyzeSourceCode$1(EOOdinAnalyzer.scala:79)
        at fs2.Stream.$anonfun$flatMap$1(Stream.scala:1188)
        at fs2.Pull$FlatMapR$1.unconsed(Pull.scala:994)
        at fs2.Pull$FlatMapR$1.out(Pull.scala:1020)
        at fs2.Pull$.$anonfun$compile$24(Pull.scala:1178)
        at fs2.Pull$.$anonfun$compile$2(Pull.scala:904)
        at analyze @ org.polystat.AnOdin.errors(AnOdin.java:51)
        at get @ fs2.internal.InterruptContext.$anonfun$eval$1(InterruptContext.scala:91)
        at get @ fs2.internal.InterruptContext.$anonfun$eval$1(InterruptContext.scala:91)

No errors found
```

**Comment by fizruk** [comment]
@nikololiahim We should fix this in Polystat and/or odin. If analyser fails, we should report that we cannot find errors (or cannot parse), not throw an exception.
