### ISSUE TITLE
Circular decoration leads to exception

### ISSUE THREAD

**Issue by someilay** [polystat/polystat#50]
Code:
```
[] > test
  [] > a
    test.b > @
  [] > b
    test.a > @
  test.b > @
```

Exception:
```
java.lang.StackOverflowError
	at org.polystat.odin.analysis.inlining.Optics$optionals$.$anonfun$mapValueAtKey$1(Optics.scala:98)
	at monocle.Optional$$anon$3.getOption(Optional.scala:241)
	at monocle.POptional$$anon$1.getOption(Optional.scala:134)
	at monocle.POptional$$anon$1.getOption(Optional.scala:134)
	at org.polystat.odin.analysis.mutualrec.advanced.Analyzer$.$anonfun$buildProgramFromObjectTree$1(Analyzer.scala:64)
	at scala.Option.flatMap(Option.scala:283)
	at org.polystat.odin.analysis.mutualrec.advanced.Analyzer$.getParentTree$1(Analyzer.scala:64)
	at org.polystat.odin.analysis.mutualrec.advanced.Analyzer$.resolveParentInfoOf$1(Analyzer.scala:77)
	at org.polystat.odin.analysis.mutualrec.advanced.Analyzer$.resolveParentInfoOf$1(Analyzer.scala:83)
	at org.polystat.odin.analysis.mutualrec.advanced.Analyzer$.resolveParentInfoOf$1(Analyzer.scala:83)
	at org.polystat.odin.analysis.mutualrec.advanced.Analyzer$.resolveParentInfoOf$1(Analyzer.scala:83)
	at org.polystat.odin.analysis.mutualrec.advanced.Analyzer$.resolveParentInfoOf$1(Analyzer.scala:83)
	at org.polystat.odin.analysis.mutualrec.advanced.Analyzer$.resolveParentInfoOf$1(Analyzer.scala:83)
...
```

**Comment by nikololiahim** [comment]
Currently tracked in [polystat/odin#26](https://github.com/polystat/odin/issues/26).
