### ISSUE TITLE
FileNotFound excepton when running compiled code from the target on tests

### ISSUE THREAD

**Issue by akuleshov7** [polystat/polystat#8]
Executing the following command:
`$ akuleshov7@DESKTOP-2BQ3IF3:/mnt/d/polystat$ java -jar target/polystat-1.0-SNAPSHOT-jar-with-dependencies.jar src test`

Getting exception:
```
Exception in thread "main" java.io.UncheckedIOException: java.io.FileNotFoundException: src/foo.eo (No such file or directory)
        at org.cactoos.scalar.Unchecked.value(Unchecked.java:58)
        at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:57)
        at org.polystat.far.Reverses.errors(Reverses.java:87)
        at org.polystat.Polystat.exec(Polystat.java:82)
        at org.polystat.Polystat.main(Polystat.java:63)
Caused by: java.io.FileNotFoundException: src/foo.eo (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at org.cactoos.io.InputOf.lambda$new$2(InputOf.java:76)
        at org.cactoos.io.InputOf.stream(InputOf.java:310)
        at org.cactoos.io.TeeInput.stream(TeeInput.java:867)
        at org.cactoos.io.InputAsBytes.asBytes(InputAsBytes.java:77)
        at org.cactoos.io.BytesOf.asBytes(BytesOf.java:341)
        at org.cactoos.text.TextOf.lambda$new$0(TextOf.java:297)
        at org.cactoos.scalar.Checked.value(Checked.java:76)
        at org.cactoos.scalar.IoChecked.value(IoChecked.java:63)
        at org.cactoos.text.TextEnvelope.asString(TextEnvelope.java:65)
        at org.eolang.parser.Syntax.parse(Syntax.java:87)
        at org.polystat.XMIR.apply(XMIR.java:81)
        at org.polystat.XMIR.apply(XMIR.java:49)
        at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:56)
        at org.cactoos.scalar.Checked.value(Checked.java:76)
        at org.cactoos.scalar.IoChecked.value(IoChecked.java:63)
        at org.cactoos.scalar.Unchecked.value(Unchecked.java:56)
        ... 4 more
```

It looks like file discovery works incorrectly and is getting the path from the root where thecoomand was executed

**Comment by yegor256** [comment]
@akuleshov7 are you sure you have the `src/foo.eo` file available? I just did what you are doing and it seems to work for me:

```bash
$ cd /code/temp
/code/temp$ mkdir src
$ mkdir src
$ cat > src/foo.eo
[x] > foo
  div. > @
    42
    x
$ java -jar /code/polystat/polystat/target/polystat-1.0-SNAPSHOT-jar-with-dependencies.jar src temp
Error: \perp at {x=0, κ-4-3=\any}
```

This is where the location of the `.eo` file is being resolved: https://github.com/polystat/polystat/blob/master/src/main/java/org/polystat/Program.java#L80 Should work on both Unix and Windows.

**Comment by mximp** [comment]
@pollyvolk please check this out.

**Comment by pollyvolk** [comment]
@mximp Could you, please, describe current requirements for the option `--files`? 

According to the option description in `Polystat.java`, the value of this option specifies a directory with EO **files**. However, as mentioned in README, the program processes a **single file** called `test.eo` ignoring other `.eo` files. 
If a user specifies, e.g., `--files sources`, but the folder `sources` doesn't contain `test.eo`, Polystat will throw an error.

Other case:  a user runs Polystat with  `--files sources --tmp result`, and there is a file `sources/test.eo`. The result of the analysis will be saved to `result/test.xml`. If the user renames or deletes the file `sources/test.eo` and runs the same command again, Polystat will print the previous correct result, taking it from `result/test.xml`, not throwing an exception.

Is it the functionality you expect to have?

**Comment by mximp** [comment]
@pollyvolk The second case is incorrect behaviour: if source is deleted the temp file should be deleted as well. 

Regarding test files: current implementation supports only single object within sources named `test`.
This needs to be enhanced (we even have several requests for this feature) so that all `.eo` files are processed.

**Comment by pollyvolk** [comment]
@mximp Do you want me to fix the second case, as it is a wrong behaviour?

**Comment by mximp** [comment]
@pollyvolk yes please.

For the sources we already have issues: #58, #18, #17
